export const ACTION = {
  CLICK_NUMBER: 'CLICK_NUMBER',
  CLICK_OPERATOR: 'CLICK_OPERATOR',
  ALL_CLEAR: 'ALL_CLEAR',
  ADD_TO_INPUT: 'ADD_TO_INPUT',
  ADD_ZERO_TO_INPUT: 'ADD_ZERO_TO_INPUT',
  ADD_DECIMAL: 'ADD_DECIMAL',
  ADD: 'ADD',
  SUBTRACT: 'SUBTRACT',
  MULTIPLY: 'MULTIPLY',
  DIVIDE: 'DIVIDE',
  ON_EQUAL: 'ON_EQUAL',
};
